// Generated by view binder compiler. Do not edit!
package com.example.hrdina.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;

import com.example.hrdina.R;

import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityNewGameBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final EditText heroNameEdit;

  @NonNull
  public final TextView nameHeroText;

  @NonNull
  public final Button startBtn;

  private ActivityNewGameBinding(@NonNull ConstraintLayout rootView, @NonNull EditText heroNameEdit,
      @NonNull TextView nameHeroText, @NonNull Button startBtn) {
    this.rootView = rootView;
    this.heroNameEdit = heroNameEdit;
    this.nameHeroText = nameHeroText;
    this.startBtn = startBtn;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityNewGameBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityNewGameBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_new_game, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityNewGameBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.heroNameEdit;
      EditText heroNameEdit = ViewBindings.findChildViewById(rootView, id);
      if (heroNameEdit == null) {
        break missingId;
      }

      id = R.id.nameHeroText;
      TextView nameHeroText = ViewBindings.findChildViewById(rootView, id);
      if (nameHeroText == null) {
        break missingId;
      }

      id = R.id.startBtn;
      Button startBtn = ViewBindings.findChildViewById(rootView, id);
      if (startBtn == null) {
        break missingId;
      }

      return new ActivityNewGameBinding((ConstraintLayout) rootView, heroNameEdit, nameHeroText,
          startBtn);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
