// Generated by view binder compiler. Do not edit!
package com.example.hrdina.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageView;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;

import com.example.hrdina.R;


public final class ActivityGameBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final ImageView imageCenter;

  @NonNull
  public final ImageView imageEast;

  @NonNull
  public final ImageView imageHealth;

  @NonNull
  public final ImageView imageMedical;

  @NonNull
  public final ImageView imageNorth;

  @NonNull
  public final ImageView imageNorthEast;

  @NonNull
  public final ImageView imageNorthWest;

  @NonNull
  public final ImageView imageRip;

  @NonNull
  public final ImageView imageShield;

  @NonNull
  public final ImageView imageSouth;

  @NonNull
  public final ImageView imageSouthEast;

  @NonNull
  public final ImageView imageSouthWest;

  @NonNull
  public final ImageView imageSword;

  @NonNull
  public final ImageView imageWest;

  @NonNull
  public final TextView textAttack;

  @NonNull
  public final TextView textDefense;

  @NonNull
  public final TextView textHealing;

  @NonNull
  public final TextView textHealth;

  @NonNull
  public final TextView textHeroName;

  @NonNull
  public final TextView textKills;

  @NonNull
  public final TextView textScore;

  private ActivityGameBinding(@NonNull ConstraintLayout rootView, @NonNull ImageView imageCenter,
      @NonNull ImageView imageEast, @NonNull ImageView imageHealth, @NonNull ImageView imageMedical,
      @NonNull ImageView imageNorth, @NonNull ImageView imageNorthEast,
      @NonNull ImageView imageNorthWest, @NonNull ImageView imageRip,
      @NonNull ImageView imageShield, @NonNull ImageView imageSouth,
      @NonNull ImageView imageSouthEast, @NonNull ImageView imageSouthWest,
      @NonNull ImageView imageSword, @NonNull ImageView imageWest, @NonNull TextView textAttack,
      @NonNull TextView textDefense, @NonNull TextView textHealing, @NonNull TextView textHealth,
      @NonNull TextView textHeroName, @NonNull TextView textKills, @NonNull TextView textScore) {
    this.rootView = rootView;
    this.imageCenter = imageCenter;
    this.imageEast = imageEast;
    this.imageHealth = imageHealth;
    this.imageMedical = imageMedical;
    this.imageNorth = imageNorth;
    this.imageNorthEast = imageNorthEast;
    this.imageNorthWest = imageNorthWest;
    this.imageRip = imageRip;
    this.imageShield = imageShield;
    this.imageSouth = imageSouth;
    this.imageSouthEast = imageSouthEast;
    this.imageSouthWest = imageSouthWest;
    this.imageSword = imageSword;
    this.imageWest = imageWest;
    this.textAttack = textAttack;
    this.textDefense = textDefense;
    this.textHealing = textHealing;
    this.textHealth = textHealth;
    this.textHeroName = textHeroName;
    this.textKills = textKills;
    this.textScore = textScore;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityGameBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityGameBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_game, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityGameBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.imageCenter;
      ImageView imageCenter = ViewBindings.findChildViewById(rootView, id);
      if (imageCenter == null) {
        break missingId;
      }

      id = R.id.imageEast;
      ImageView imageEast = ViewBindings.findChildViewById(rootView, id);
      if (imageEast == null) {
        break missingId;
      }

      id = R.id.imageHealth;
      ImageView imageHealth = ViewBindings.findChildViewById(rootView, id);
      if (imageHealth == null) {
        break missingId;
      }

      id = R.id.imageMedical;
      ImageView imageMedical = ViewBindings.findChildViewById(rootView, id);
      if (imageMedical == null) {
        break missingId;
      }

      id = R.id.imageNorth;
      ImageView imageNorth = ViewBindings.findChildViewById(rootView, id);
      if (imageNorth == null) {
        break missingId;
      }

      id = R.id.imageNorthEast;
      ImageView imageNorthEast = ViewBindings.findChildViewById(rootView, id);
      if (imageNorthEast == null) {
        break missingId;
      }

      id = R.id.imageNorthWest;
      ImageView imageNorthWest = ViewBindings.findChildViewById(rootView, id);
      if (imageNorthWest == null) {
        break missingId;
      }

      id = R.id.imageRip;
      ImageView imageRip = ViewBindings.findChildViewById(rootView, id);
      if (imageRip == null) {
        break missingId;
      }

      id = R.id.imageShield;
      ImageView imageShield = ViewBindings.findChildViewById(rootView, id);
      if (imageShield == null) {
        break missingId;
      }

      id = R.id.imageSouth;
      ImageView imageSouth = ViewBindings.findChildViewById(rootView, id);
      if (imageSouth == null) {
        break missingId;
      }

      id = R.id.imageSouthEast;
      ImageView imageSouthEast = ViewBindings.findChildViewById(rootView, id);
      if (imageSouthEast == null) {
        break missingId;
      }

      id = R.id.imageSouthWest;
      ImageView imageSouthWest = ViewBindings.findChildViewById(rootView, id);
      if (imageSouthWest == null) {
        break missingId;
      }

      id = R.id.imageSword;
      ImageView imageSword = ViewBindings.findChildViewById(rootView, id);
      if (imageSword == null) {
        break missingId;
      }

      id = R.id.imageWest;
      ImageView imageWest = ViewBindings.findChildViewById(rootView, id);
      if (imageWest == null) {
        break missingId;
      }

      id = R.id.textAttack;
      TextView textAttack = ViewBindings.findChildViewById(rootView, id);
      if (textAttack == null) {
        break missingId;
      }

      id = R.id.textDefense;
      TextView textDefense = ViewBindings.findChildViewById(rootView, id);
      if (textDefense == null) {
        break missingId;
      }

      id = R.id.textHealing;
      TextView textHealing = ViewBindings.findChildViewById(rootView, id);
      if (textHealing == null) {
        break missingId;
      }

      id = R.id.textHealth;
      TextView textHealth = ViewBindings.findChildViewById(rootView, id);
      if (textHealth == null) {
        break missingId;
      }

      id = R.id.textHeroName;
      TextView textHeroName = ViewBindings.findChildViewById(rootView, id);
      if (textHeroName == null) {
        break missingId;
      }

      id = R.id.textKills;
      TextView textKills = ViewBindings.findChildViewById(rootView, id);
      if (textKills == null) {
        break missingId;
      }

      id = R.id.textScore;
      TextView textScore = ViewBindings.findChildViewById(rootView, id);
      if (textScore == null) {
        break missingId;
      }

      return new ActivityGameBinding((ConstraintLayout) rootView, imageCenter, imageEast,
          imageHealth, imageMedical, imageNorth, imageNorthEast, imageNorthWest, imageRip,
          imageShield, imageSouth, imageSouthEast, imageSouthWest, imageSword, imageWest,
          textAttack, textDefense, textHealing, textHealth, textHeroName, textKills, textScore);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
